### ISSUE TITLE
NumPy 'bool' attribute has been deprecated

### ISSUE THREAD

**Issue by tenbravemen** [LinkedInLearning/artificial-intelligence-foundations-neural-networks-4381282#2]
## Issue Overview
When writing the code to visualize a correlation, using the NumPy "bool" attribute threw the following error:  "AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations"

## Describe your environment
Using Google Colab connected to GitHub

## Possible Solution
Use 'np.bool_ ' instead of 'np.bool'

**Comment by khannoussi-malek** [comment]
I'd like to take on this task and update the codebase to use `np.bool_` instead. I'll ensure all instances are corrected and the code remains compatible with the latest version of NumPy.

**Comment by tenbravemen** [comment]
Thank you!
